/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MobileHomeRouteImport } from './routes/mobile-home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthPendingRouteImport } from './routes/auth-pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TransfersTransferIdRouteImport } from './routes/transfers.$transferId'
import { Route as LoansNewRouteImport } from './routes/loans.new'
import { Route as LoansLoanIdRouteImport } from './routes/loans.$loanId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRepaymentRouteImport } from './routes/legal.repayment'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalMentionsRouteImport } from './routes/legal.mentions'
import { Route as LegalLoanTermsRouteImport } from './routes/legal.loan-terms'
import { Route as LegalFinancialPrivacyRouteImport } from './routes/legal.financial-privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAmlKycRouteImport } from './routes/legal.aml-kyc'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLoansRouteImport } from './routes/admin.loans'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminTransfersIndexRouteImport } from './routes/admin.transfers.index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminChatIndexRouteImport } from './routes/admin.chat.index'
import { Route as TransfersTransferIdReceiptRouteImport } from './routes/transfers.$transferId.receipt'
import { Route as AdminTransfersNewRouteImport } from './routes/admin.transfers.new'
import { Route as AdminClientsUserIdRouteImport } from './routes/admin.clients.$userId'
import { Route as AdminChatConversationIdRouteImport } from './routes/admin.chat.$conversationId'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileHomeRoute = MobileHomeRouteImport.update({
  id: '/mobile-home',
  path: '/mobile-home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingRoute = AuthPendingRouteImport.update({
  id: '/auth-pending',
  path: '/auth-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransfersRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TransfersTransferIdRoute = TransfersTransferIdRouteImport.update({
  id: '/$transferId',
  path: '/$transferId',
  getParentRoute: () => TransfersRoute,
} as any)
const LoansNewRoute = LoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansLoanIdRoute = LoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRepaymentRoute = LegalRepaymentRouteImport.update({
  id: '/legal/repayment',
  path: '/legal/repayment',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLoanTermsRoute = LegalLoanTermsRouteImport.update({
  id: '/legal/loan-terms',
  path: '/legal/loan-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFinancialPrivacyRoute = LegalFinancialPrivacyRouteImport.update({
  id: '/legal/financial-privacy',
  path: '/legal/financial-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAmlKycRoute = LegalAmlKycRouteImport.update({
  id: '/legal/aml-kyc',
  path: '/legal/aml-kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoansRoute = AdminLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransfersIndexRoute = AdminTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatIndexRoute = AdminChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminChatRoute,
} as any)
const TransfersTransferIdReceiptRoute =
  TransfersTransferIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => TransfersTransferIdRoute,
  } as any)
const AdminTransfersNewRoute = AdminTransfersNewRouteImport.update({
  id: '/transfers/new',
  path: '/transfers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsUserIdRoute = AdminClientsUserIdRouteImport.update({
  id: '/clients/$userId',
  path: '/clients/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatConversationIdRoute = AdminChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AdminChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth-pending': typeof AuthPendingRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/mobile-home': typeof MobileHomeRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/admin/chat': typeof AdminChatRouteWithChildren
  '/admin/loans': typeof AdminLoansRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/new': typeof LoansNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/admin/chat/$conversationId': typeof AdminChatConversationIdRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/transfers/new': typeof AdminTransfersNewRoute
  '/transfers/$transferId/receipt': typeof TransfersTransferIdReceiptRoute
  '/admin/chat/': typeof AdminChatIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/transfers/': typeof AdminTransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth-pending': typeof AuthPendingRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/mobile-home': typeof MobileHomeRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/new': typeof LoansNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/admin/chat/$conversationId': typeof AdminChatConversationIdRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/transfers/new': typeof AdminTransfersNewRoute
  '/transfers/$transferId/receipt': typeof TransfersTransferIdReceiptRoute
  '/admin/chat': typeof AdminChatIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/transfers': typeof AdminTransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth-pending': typeof AuthPendingRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/mobile-home': typeof MobileHomeRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/admin/chat': typeof AdminChatRouteWithChildren
  '/admin/loans': typeof AdminLoansRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/aml-kyc': typeof LegalAmlKycRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/financial-privacy': typeof LegalFinancialPrivacyRoute
  '/legal/loan-terms': typeof LegalLoanTermsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/repayment': typeof LegalRepaymentRoute
  '/legal/terms': typeof LegalTermsRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/new': typeof LoansNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/admin/chat/$conversationId': typeof AdminChatConversationIdRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/transfers/new': typeof AdminTransfersNewRoute
  '/transfers/$transferId/receipt': typeof TransfersTransferIdReceiptRoute
  '/admin/chat/': typeof AdminChatIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/transfers/': typeof AdminTransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-pending'
    | '/chat'
    | '/contact'
    | '/dashboard'
    | '/mobile-home'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/transfers'
    | '/admin/chat'
    | '/admin/loans'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/loans/$loanId'
    | '/loans/new'
    | '/transfers/$transferId'
    | '/admin/'
    | '/transfers/'
    | '/admin/chat/$conversationId'
    | '/admin/clients/$userId'
    | '/admin/transfers/new'
    | '/transfers/$transferId/receipt'
    | '/admin/chat/'
    | '/admin/clients/'
    | '/admin/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-pending'
    | '/chat'
    | '/contact'
    | '/dashboard'
    | '/mobile-home'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/admin/loans'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/loans/$loanId'
    | '/loans/new'
    | '/transfers/$transferId'
    | '/admin'
    | '/transfers'
    | '/admin/chat/$conversationId'
    | '/admin/clients/$userId'
    | '/admin/transfers/new'
    | '/transfers/$transferId/receipt'
    | '/admin/chat'
    | '/admin/clients'
    | '/admin/transfers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-pending'
    | '/chat'
    | '/contact'
    | '/dashboard'
    | '/mobile-home'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/transfers'
    | '/admin/chat'
    | '/admin/loans'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/staff'
    | '/admin/verify'
    | '/auth/callback'
    | '/legal/aml-kyc'
    | '/legal/cookies'
    | '/legal/financial-privacy'
    | '/legal/loan-terms'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/legal/repayment'
    | '/legal/terms'
    | '/loans/$loanId'
    | '/loans/new'
    | '/transfers/$transferId'
    | '/admin/'
    | '/transfers/'
    | '/admin/chat/$conversationId'
    | '/admin/clients/$userId'
    | '/admin/transfers/new'
    | '/transfers/$transferId/receipt'
    | '/admin/chat/'
    | '/admin/clients/'
    | '/admin/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthPendingRoute: typeof AuthPendingRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  MobileHomeRoute: typeof MobileHomeRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TransfersRoute: typeof TransfersRouteWithChildren
  LegalAmlKycRoute: typeof LegalAmlKycRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalFinancialPrivacyRoute: typeof LegalFinancialPrivacyRoute
  LegalLoanTermsRoute: typeof LegalLoanTermsRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRepaymentRoute: typeof LegalRepaymentRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LoansLoanIdRoute: typeof LoansLoanIdRoute
  LoansNewRoute: typeof LoansNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-home': {
      id: '/mobile-home'
      path: '/mobile-home'
      fullPath: '/mobile-home'
      preLoaderRoute: typeof MobileHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-pending': {
      id: '/auth-pending'
      path: '/auth-pending'
      fullPath: '/auth-pending'
      preLoaderRoute: typeof AuthPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/transfers/$transferId': {
      id: '/transfers/$transferId'
      path: '/$transferId'
      fullPath: '/transfers/$transferId'
      preLoaderRoute: typeof TransfersTransferIdRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/loans/new': {
      id: '/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof LoansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$loanId': {
      id: '/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof LoansLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/repayment': {
      id: '/legal/repayment'
      path: '/legal/repayment'
      fullPath: '/legal/repayment'
      preLoaderRoute: typeof LegalRepaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/loan-terms': {
      id: '/legal/loan-terms'
      path: '/legal/loan-terms'
      fullPath: '/legal/loan-terms'
      preLoaderRoute: typeof LegalLoanTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/financial-privacy': {
      id: '/legal/financial-privacy'
      path: '/legal/financial-privacy'
      fullPath: '/legal/financial-privacy'
      preLoaderRoute: typeof LegalFinancialPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aml-kyc': {
      id: '/legal/aml-kyc'
      path: '/legal/aml-kyc'
      fullPath: '/legal/aml-kyc'
      preLoaderRoute: typeof LegalAmlKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loans': {
      id: '/admin/loans'
      path: '/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminLoansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transfers/': {
      id: '/admin/transfers/'
      path: '/transfers'
      fullPath: '/admin/transfers/'
      preLoaderRoute: typeof AdminTransfersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat/': {
      id: '/admin/chat/'
      path: '/'
      fullPath: '/admin/chat/'
      preLoaderRoute: typeof AdminChatIndexRouteImport
      parentRoute: typeof AdminChatRoute
    }
    '/transfers/$transferId/receipt': {
      id: '/transfers/$transferId/receipt'
      path: '/receipt'
      fullPath: '/transfers/$transferId/receipt'
      preLoaderRoute: typeof TransfersTransferIdReceiptRouteImport
      parentRoute: typeof TransfersTransferIdRoute
    }
    '/admin/transfers/new': {
      id: '/admin/transfers/new'
      path: '/transfers/new'
      fullPath: '/admin/transfers/new'
      preLoaderRoute: typeof AdminTransfersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$userId': {
      id: '/admin/clients/$userId'
      path: '/clients/$userId'
      fullPath: '/admin/clients/$userId'
      preLoaderRoute: typeof AdminClientsUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat/$conversationId': {
      id: '/admin/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/admin/chat/$conversationId'
      preLoaderRoute: typeof AdminChatConversationIdRouteImport
      parentRoute: typeof AdminChatRoute
    }
  }
}

interface AdminChatRouteChildren {
  AdminChatConversationIdRoute: typeof AdminChatConversationIdRoute
  AdminChatIndexRoute: typeof AdminChatIndexRoute
}

const AdminChatRouteChildren: AdminChatRouteChildren = {
  AdminChatConversationIdRoute: AdminChatConversationIdRoute,
  AdminChatIndexRoute: AdminChatIndexRoute,
}

const AdminChatRouteWithChildren = AdminChatRoute._addFileChildren(
  AdminChatRouteChildren,
)

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRouteWithChildren
  AdminLoansRoute: typeof AdminLoansRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsUserIdRoute: typeof AdminClientsUserIdRoute
  AdminTransfersNewRoute: typeof AdminTransfersNewRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminTransfersIndexRoute: typeof AdminTransfersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRouteWithChildren,
  AdminLoansRoute: AdminLoansRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsUserIdRoute: AdminClientsUserIdRoute,
  AdminTransfersNewRoute: AdminTransfersNewRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminTransfersIndexRoute: AdminTransfersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TransfersTransferIdRouteChildren {
  TransfersTransferIdReceiptRoute: typeof TransfersTransferIdReceiptRoute
}

const TransfersTransferIdRouteChildren: TransfersTransferIdRouteChildren = {
  TransfersTransferIdReceiptRoute: TransfersTransferIdReceiptRoute,
}

const TransfersTransferIdRouteWithChildren =
  TransfersTransferIdRoute._addFileChildren(TransfersTransferIdRouteChildren)

interface TransfersRouteChildren {
  TransfersTransferIdRoute: typeof TransfersTransferIdRouteWithChildren
  TransfersIndexRoute: typeof TransfersIndexRoute
}

const TransfersRouteChildren: TransfersRouteChildren = {
  TransfersTransferIdRoute: TransfersTransferIdRouteWithChildren,
  TransfersIndexRoute: TransfersIndexRoute,
}

const TransfersRouteWithChildren = TransfersRoute._addFileChildren(
  TransfersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthPendingRoute: AuthPendingRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  MobileHomeRoute: MobileHomeRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TransfersRoute: TransfersRouteWithChildren,
  LegalAmlKycRoute: LegalAmlKycRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalFinancialPrivacyRoute: LegalFinancialPrivacyRoute,
  LegalLoanTermsRoute: LegalLoanTermsRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRepaymentRoute: LegalRepaymentRoute,
  LegalTermsRoute: LegalTermsRoute,
  LoansLoanIdRoute: LoansLoanIdRoute,
  LoansNewRoute: LoansNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
